services:
  vue:
    #image: baiyuetribe/kamiFaka:vue
    build:
      context: .
      dockerfile: dist.dockerfile    
    container_name: kamiaFaka-vue
    restart: always
    ports:
      - 999:80
  flask:
    #image: baiyuetribe/kamiFaka:flask
    build: .
    container_name: kamiaFaka-flask
    restart: always
    ports:
      - 5000:5000
