version: '3.1'

services:
  kamifaka:
    image: baiyuetribe/kamifaka
    restart: always
    environment:
      DB_TYPE: Sqlite
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: kamifaka
    # volumes:
    #   - /opt/kamifaka:/usr/src/app/public
    ports:
      - 8000:8000
